// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/PoseStamped
// </auto-generated>
using Rclsharp.Cdr;
using Rclsharp.Msgs.Std;

namespace Rclsharp.Msgs.Geometry;

/// <summary>
/// geometry_msgs/msg/PoseStamped の C# 表現 (生成コード)。
/// </summary>
public struct PoseStamped
{
    public const string RosTypeName = "geometry_msgs/msg/PoseStamped";
    public const string DdsTypeName = "geometry_msgs::msg::dds_::PoseStamped_";

    public Header Header;
    public Pose Pose;

    public PoseStamped(Header header, Pose pose)
    {
        Header = header;
        Pose = pose;
    }

    public override string ToString() => $"PoseStamped(header={Header}, pose={Pose})";
}

public sealed class PoseStampedSerializer : ICdrSerializer<PoseStamped>
{
    public static readonly PoseStampedSerializer Instance = new();

    public bool IsKeyed => false;

    public int GetSerializedSize(in PoseStamped value)
    {
        int total = 0;
        total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
        total += 7;
        total += PoseSerializer.Instance.GetSerializedSize(in value.Pose);
        return total;
    }

    public void Serialize(ref CdrWriter writer, in PoseStamped value)
    {
        HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
        PoseSerializer.Instance.Serialize(ref writer, in value.Pose);
    }

    public void Deserialize(ref CdrReader reader, out PoseStamped value)
    {
        HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
        PoseSerializer.Instance.Deserialize(ref reader, out Pose pose);
        value = new PoseStamped(header, pose);
    }

    public void SerializeKey(ref CdrWriter writer, in PoseStamped value)
    {
    }
}
