// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: geometry_msgs/msg/Pose
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.Geometry
{
    /// <summary>
    /// geometry_msgs/msg/Pose の C# 表現 (生成コード)。
    /// </summary>
    public struct Pose
    {
        public const string RosTypeName = "geometry_msgs/msg/Pose";
        public const string DdsTypeName = "geometry_msgs::msg::dds_::Pose_";

        public Point Position;
        public Quaternion Orientation;

        public Pose(Point position, Quaternion orientation)
        {
            Position = position;
            Orientation = orientation;
        }

        public override string ToString() => $"Pose(position={Position}, orientation={Orientation})";
    }

    public sealed class PoseSerializer : ICdrSerializer<Pose>
    {
        public static readonly PoseSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Pose value)
        {
            int total = 0;
            total += PointSerializer.Instance.GetSerializedSize(in value.Position);
            total += QuaternionSerializer.Instance.GetSerializedSize(in value.Orientation);
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Pose value)
        {
            PointSerializer.Instance.Serialize(ref writer, in value.Position);
            QuaternionSerializer.Instance.Serialize(ref writer, in value.Orientation);
        }

        public void Deserialize(ref CdrReader reader, out Pose value)
        {
            PointSerializer.Instance.Deserialize(ref reader, out Point position);
            QuaternionSerializer.Instance.Deserialize(ref reader, out Quaternion orientation);
            value = new Pose(position, orientation);
        }

        public void SerializeKey(ref CdrWriter writer, in Pose value)
        {
        }
    }
}
