// <auto-generated>
//     このファイルは rclsharp-genmsg により生成されました。手動で編集しないでください。
//     source: std_msgs/msg/Header
// </auto-generated>
using Rclsharp.Cdr;
using Rclsharp.Msgs.BuiltinInterfaces;

namespace Rclsharp.Msgs.Std;

/// <summary>
/// std_msgs/msg/Header の C# 表現 (生成コード)。
/// </summary>
public struct Header
{
    public const string RosTypeName = "std_msgs/msg/Header";
    public const string DdsTypeName = "std_msgs::msg::dds_::Header_";

    public Time Stamp;
    public string FrameId;

    public Header(Time stamp, string frameId)
    {
        Stamp = stamp;
        FrameId = frameId;
    }

    public override string ToString() => $"Header(stamp={Stamp}, frame_id={FrameId})";
}

public sealed class HeaderSerializer : ICdrSerializer<Header>
{
    public static readonly HeaderSerializer Instance = new();

    public bool IsKeyed => false;

    public int GetSerializedSize(in Header value)
    {
        int total = 0;
        total += TimeSerializer.Instance.GetSerializedSize(in value.Stamp);
        int lenFrameId = value.FrameId is null ? 0 : System.Text.Encoding.UTF8.GetByteCount(value.FrameId);
        total += 4 + lenFrameId + 1;
        return total;
    }

    public void Serialize(ref CdrWriter writer, in Header value)
    {
        TimeSerializer.Instance.Serialize(ref writer, in value.Stamp);
        writer.WriteString(value.FrameId);
    }

    public void Deserialize(ref CdrReader reader, out Header value)
    {
        TimeSerializer.Instance.Deserialize(ref reader, out Time stamp);
        string frameId = reader.ReadString();
        value = new Header(stamp, frameId);
    }

    public void SerializeKey(ref CdrWriter writer, in Header value)
    {
    }
}
