// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: builtin_interfaces/msg/Duration
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.BuiltinInterfaces
{
    /// <summary>
    /// builtin_interfaces/msg/Duration の C# 表現 (生成コード)。
    /// </summary>
    public struct Duration
    {
        public const string RosTypeName = "builtin_interfaces/msg/Duration";
        public const string DdsTypeName = "builtin_interfaces::msg::dds_::Duration_";

        public int Sec;
        public uint Nanosec;

        public Duration(int sec, uint nanosec)
        {
            Sec = sec;
            Nanosec = nanosec;
        }

        public override string ToString() => $"Duration(sec={Sec}, nanosec={Nanosec})";
    }

    public sealed class DurationSerializer : ICdrSerializer<Duration>
    {
        public static readonly DurationSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Duration value)
        {
            int total = 0;
            total += 4;
            total += 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Duration value)
        {
            writer.WriteInt32(value.Sec);
            writer.WriteUInt32(value.Nanosec);
        }

        public void Deserialize(ref CdrReader reader, out Duration value)
        {
            int sec = reader.ReadInt32();
            uint nanosec = reader.ReadUInt32();
            value = new Duration(sec, nanosec);
        }

        public void SerializeKey(ref CdrWriter writer, in Duration value)
        {
        }
    }
}
