// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: builtin_interfaces/msg/Time
// </auto-generated>
using ROSettaDDS.Cdr;

namespace ROSettaDDS.Msgs.BuiltinInterfaces
{
    /// <summary>
    /// builtin_interfaces/msg/Time の C# 表現 (生成コード)。
    /// </summary>
    public struct Time
    {
        public const string RosTypeName = "builtin_interfaces/msg/Time";
        public const string DdsTypeName = "builtin_interfaces::msg::dds_::Time_";

        public int Sec;
        public uint Nanosec;

        public Time(int sec, uint nanosec)
        {
            Sec = sec;
            Nanosec = nanosec;
        }

        public override string ToString() => $"Time(sec={Sec}, nanosec={Nanosec})";
    }

    public sealed class TimeSerializer : ICdrSerializer<Time>
    {
        public static readonly TimeSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in Time value)
        {
            int total = 0;
            total += 4;
            total += 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in Time value)
        {
            writer.WriteInt32(value.Sec);
            writer.WriteUInt32(value.Nanosec);
        }

        public void Deserialize(ref CdrReader reader, out Time value)
        {
            int sec = reader.ReadInt32();
            uint nanosec = reader.ReadUInt32();
            value = new Time(sec, nanosec);
        }

        public void SerializeKey(ref CdrWriter writer, in Time value)
        {
        }
    }
}
