// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: teleop_ik/msg/ResetCommand
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.TeleopIk
{
    /// <summary>
    /// teleop_ik/msg/ResetCommand の C# 表現 (生成コード)。
    /// </summary>
    public struct ResetCommand
    {
        public const string RosTypeName = "teleop_ik/msg/ResetCommand";
        public const string DdsTypeName = "teleop_ik::msg::dds_::ResetCommand_";

        public Header Header;
        public float[] HomeJoints;
        public float DurationSec;

        public ResetCommand(Header header, float[] homeJoints, float durationSec)
        {
            Header = header;
            HomeJoints = homeJoints;
            DurationSec = durationSec;
        }

        public override string ToString() => $"ResetCommand(header={Header}, home_joints=[{(HomeJoints is null ? 0 : HomeJoints.Length)}], duration_sec={DurationSec})";
    }

    public sealed class ResetCommandSerializer : ICdrSerializer<ResetCommand>
    {
        public static readonly ResetCommandSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in ResetCommand value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 3;
            total += 6 * 4;
            total += 3;
            total += 4;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in ResetCommand value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            var arrHomeJoints = value.HomeJoints ?? new float[6];
            for (int i = 0; i < 6; i++)
            {
                writer.WriteFloat(arrHomeJoints[i]);
            }
            writer.WriteFloat(value.DurationSec);
        }

        public void Deserialize(ref CdrReader reader, out ResetCommand value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            var homeJoints = new float[6];
            for (int i = 0; i < 6; i++)
            {
                homeJoints[i] = reader.ReadFloat();
            }
            float durationSec = reader.ReadFloat();
            value = new ResetCommand(header, homeJoints, durationSec);
        }

        public void SerializeKey(ref CdrWriter writer, in ResetCommand value)
        {
        }
    }
}
