// <auto-generated>
//     このファイルは rosettadds-genmsg により生成されました。手動で編集しないでください。
//     source: teleop_ik/msg/TargetPoseWithInput
// </auto-generated>
using ROSettaDDS.Cdr;
using ROSettaDDS.Msgs.Geometry;
using ROSettaDDS.Msgs.Std;

namespace ROSettaDDS.Msgs.TeleopIk
{
    /// <summary>
    /// teleop_ik/msg/TargetPoseWithInput の C# 表現 (生成コード)。
    /// </summary>
    public struct TargetPoseWithInput
    {
        public const string RosTypeName = "teleop_ik/msg/TargetPoseWithInput";
        public const string DdsTypeName = "teleop_ik::msg::dds_::TargetPoseWithInput_";

        public Header Header;
        public Pose Pose;
        public float StickX;
        public float StickY;
        public bool IkActive;

        public TargetPoseWithInput(Header header, Pose pose, float stickX, float stickY, bool ikActive)
        {
            Header = header;
            Pose = pose;
            StickX = stickX;
            StickY = stickY;
            IkActive = ikActive;
        }

        public override string ToString() => $"TargetPoseWithInput(header={Header}, pose={Pose}, stick_x={StickX}, stick_y={StickY}, ik_active={IkActive})";
    }

    public sealed class TargetPoseWithInputSerializer : ICdrSerializer<TargetPoseWithInput>
    {
        public static readonly TargetPoseWithInputSerializer Instance = new();

        public bool IsKeyed => false;

        public int GetSerializedSize(in TargetPoseWithInput value)
        {
            int total = 0;
            total += HeaderSerializer.Instance.GetSerializedSize(in value.Header);
            total += 7;
            total += PoseSerializer.Instance.GetSerializedSize(in value.Pose);
            total += 3;
            total += 4;
            total += 3;
            total += 4;
            total += 1;
            return total;
        }

        public void Serialize(ref CdrWriter writer, in TargetPoseWithInput value)
        {
            HeaderSerializer.Instance.Serialize(ref writer, in value.Header);
            PoseSerializer.Instance.Serialize(ref writer, in value.Pose);
            writer.WriteFloat(value.StickX);
            writer.WriteFloat(value.StickY);
            writer.WriteBool(value.IkActive);
        }

        public void Deserialize(ref CdrReader reader, out TargetPoseWithInput value)
        {
            HeaderSerializer.Instance.Deserialize(ref reader, out Header header);
            PoseSerializer.Instance.Deserialize(ref reader, out Pose pose);
            float stickX = reader.ReadFloat();
            float stickY = reader.ReadFloat();
            bool ikActive = reader.ReadBool();
            value = new TargetPoseWithInput(header, pose, stickX, stickY, ikActive);
        }

        public void SerializeKey(ref CdrWriter writer, in TargetPoseWithInput value)
        {
        }
    }
}
