# Automatically generated by: ros2nix --distro jazzy --output-dir nix --output-as-nix-pkg-name --nixfmt
{
  lib,
  buildRosPackage,
  ament-cmake,
  fmt,
  hardware-interface,
  libserial-dev,
  lifecycle-msgs,
  pkg-config,
  pluginlib,
  range-v3,
  rclcpp,
  rclcpp-lifecycle,
  sensor-msgs,
  spdlog,
  std-srvs,
  tl-expected,
}:
buildRosPackage rec {
  pname = "ros-jazzy-feetech-ros2-driver";
  version = "0.2.1";

  src = ./../src/feetech_ros2_driver;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    fmt
    hardware-interface
    libserial-dev
    lifecycle-msgs
    pkg-config
    pluginlib
    range-v3
    rclcpp
    rclcpp-lifecycle
    sensor-msgs
    spdlog
    std-srvs
    tl-expected
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ros2_control hardware interface for Feetech Servos";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
