# Automatically generated by: ros2nix --distro jazzy --output-dir nix --output-as-nix-pkg-name --nixfmt
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  controller-manager,
  joint-state-publisher-gui,
  lerobot-description,
  moveit-configs-utils,
  rclcpp,
  robot-state-publisher,
  ros2launch,
  rviz2,
  sensor-msgs,
  trajectory-msgs,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-lerobot-controller";
  version = "0.0.0";

  src = ./../src/lerobot_controller;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    controller-manager
    joint-state-publisher-gui
    lerobot-description
    moveit-configs-utils
    rclcpp
    robot-state-publisher
    ros2launch
    rviz2
    sensor-msgs
    trajectory-msgs
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package for controlling the LeRobot SO101 robotic arm using ROS 2 Control,
    including launch files and configuration for simulation and real hardware.";
    license = with lib.licenses; [ asl20 ];
  };
}
