# Automatically generated by: ros2nix --distro jazzy --output-dir nix --output-as-nix-pkg-name --nixfmt
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  joint-state-publisher-gui,
  robot-state-publisher,
  ros-gz-bridge,
  ros-gz-sim,
  ros2launch,
  rviz2,
  urdf,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-lerobot-description";
  version = "0.0.0";

  src = ./../src/lerobot_description;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    joint-state-publisher-gui
    robot-state-publisher
    ros-gz-bridge
    ros-gz-sim
    ros2launch
    rviz2
    urdf
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package providing the description files (URDF/Xacro), launch files, and
    configuration for the LeRobot SO101 robotic arm, supporting simulation and visualization in ROS
    2.";
    license = with lib.licenses; [ asl20 ];
  };
}
