# Automatically generated by: ros2nix --distro jazzy --output-dir nix --output-as-nix-pkg-name --nixfmt
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  lerobot-description,
  moveit-configs-utils,
  ros2launch,
  rviz2,
}:
buildRosPackage rec {
  pname = "ros-jazzy-lerobot-moveit";
  version = "0.0.0";

  src = ./../src/lerobot_moveit;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    lerobot-description
    moveit-configs-utils
    ros2launch
    rviz2
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 package providing MoveIt 2 configuration, launch files, and integration for
    the LeRobot SO101 robotic arm, enabling motion planning and manipulation in simulation or with
    real hardware.";
    license = with lib.licenses; [ asl20 ];
  };
}
