/**:
  controller_manager:
    ros__parameters:
      update_rate: 50 # Hz (higher rate for leader to capture motion accurately)

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
